//! Copilot CLI BYOK 配置管理
//!
//! Copilot CLI 通过环境变量配置 BYOK，无持久配置文件。
//! 切换供应商时：
//! 1. 将 env vars 写入预设文件（`~/.cc-switch/copilot-env.sh` / `.ps1`）
//! 2. 生成 `ccopilot` 包装脚本，加载预设文件后执行 `copilot`
//!    用户以 `ccopilot` 代替 `copilot` 即可获得 BYOK 配置

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use crate::config::get_home_dir;
use crate::error::AppError;

/// 所有已知的 Copilot CLI BYOK 环境变量名
///
/// 切换供应商时先 unset 这些 key，再写入新值，避免旧供应商配置残留。
pub const COPILOT_ALL_ENV_KEYS: &[&str] = &[
    "COPILOT_PROVIDER_BASE_URL",
    "COPILOT_PROVIDER_TYPE",
    "COPILOT_PROVIDER_API_KEY",
    "COPILOT_PROVIDER_BEARER_TOKEN",
    "COPILOT_PROVIDER_WIRE_API",
    "COPILOT_PROVIDER_AZURE_API_VERSION",
    "COPILOT_MODEL",
    "COPILOT_PROVIDER_MODEL_ID",
    "COPILOT_PROVIDER_WIRE_MODEL",
    "COPILOT_PROVIDER_MAX_PROMPT_TOKENS",
    "COPILOT_PROVIDER_MAX_OUTPUT_TOKENS",
];

/// CC-Switch 工作目录路径 `~/.cc-switch/`
fn get_cc_switch_dir() -> PathBuf {
    get_home_dir().join(".cc-switch")
}

/// Copilot env 脚本路径（Bash/Zsh）：`~/.cc-switch/copilot-env.sh`
pub fn get_copilot_env_script_path_sh() -> PathBuf {
    get_cc_switch_dir().join("copilot-env.sh")
}

/// Copilot env 脚本路径（PowerShell）：`~/.cc-switch/copilot-env.ps1`
pub fn get_copilot_env_script_path_ps1() -> PathBuf {
    get_cc_switch_dir().join("copilot-env.ps1")
}

/// 将 Copilot BYOK env vars 写入预设文件
///
/// 生成 `~/.cc-switch/copilot-env.sh`（Bash/Zsh export 语句）
/// 和 `~/.cc-switch/copilot-env.ps1`（PowerShell $env: 语句）。
/// 这些文件由 `ccopilot` 包装脚本自动加载，无需手动 source。
pub fn write_copilot_env_scripts(env_vars: &HashMap<String, String>) -> Result<(), AppError> {
    let dir = get_cc_switch_dir();
    fs::create_dir_all(&dir).map_err(|e| {
        AppError::localized(
            "copilot.create_dir_failed",
            format!("创建 .cc-switch 目录失败: {e}"),
            format!("Failed to create .cc-switch directory: {e}"),
        )
    })?;

    // ── Bash/Zsh 预设文件 ──
    let mut sh_lines = vec![
        "#!/usr/bin/env sh".to_string(),
        "# Auto-generated by CC-Switch – loaded automatically by the ccopilot wrapper.".to_string(),
        "# You can also source this file manually: . ~/.cc-switch/copilot-env.sh".to_string(),
        String::new(),
    ];
    // 先 unset 所有已知 key，避免旧配置残留
    for key in COPILOT_ALL_ENV_KEYS {
        sh_lines.push(format!("unset {key}"));
    }
    sh_lines.push(String::new());
    for (k, v) in env_vars {
        let escaped = v.replace('\'', "'\\''");
        sh_lines.push(format!("export {k}='{escaped}'"));
    }
    let sh_content = sh_lines.join("\n") + "\n";
    fs::write(get_copilot_env_script_path_sh(), &sh_content).map_err(|e| {
        AppError::localized(
            "copilot.write_sh_failed",
            format!("写入 copilot-env.sh 失败: {e}"),
            format!("Failed to write copilot-env.sh: {e}"),
        )
    })?;

    // ── PowerShell 预设文件 ──
    let mut ps1_lines = vec![
        "# Auto-generated by CC-Switch – loaded automatically by the ccopilot wrapper.".to_string(),
        "# You can also dot-source this file manually: . ~/.cc-switch/copilot-env.ps1".to_string(),
        String::new(),
    ];
    for key in COPILOT_ALL_ENV_KEYS {
        ps1_lines.push(format!(
            "Remove-Item Env:{key} -ErrorAction SilentlyContinue"
        ));
    }
    ps1_lines.push(String::new());
    for (k, v) in env_vars {
        let escaped = v.replace('\'', "''");
        ps1_lines.push(format!("$env:{k} = '{escaped}'"));
    }
    let ps1_content = ps1_lines.join("\r\n") + "\r\n";
    fs::write(get_copilot_env_script_path_ps1(), &ps1_content).map_err(|e| {
        AppError::localized(
            "copilot.write_ps1_failed",
            format!("写入 copilot-env.ps1 失败: {e}"),
            format!("Failed to write copilot-env.ps1: {e}"),
        )
    })?;

    Ok(())
}

/// 生成 `ccopilot` 包装脚本
///
/// 脚本加载 `~/.cc-switch/copilot-env.*` 预设文件，然后执行 `copilot`，
/// 用户以 `ccopilot` 代替 `copilot` 即可在任意终端中使用 BYOK 配置。
///
/// 生成：
/// - `~/.cc-switch/ccopilot`（sh，Unix/macOS/Linux）
/// - `~/.cc-switch/ccopilot.ps1`（PowerShell，Windows/跨平台）
/// - `~/.cc-switch/ccopilot.cmd`（CMD 批处理，Windows 便捷入口）
pub fn write_ccopilot_wrapper() -> Result<(), AppError> {
    let dir = get_cc_switch_dir();
    fs::create_dir_all(&dir).map_err(|e| {
        AppError::localized(
            "copilot.create_dir_failed",
            format!("创建 .cc-switch 目录失败: {e}"),
            format!("Failed to create .cc-switch directory: {e}"),
        )
    })?;

    // ── Unix/macOS/Linux sh 包装脚本 ──
    let sh_wrapper = r#"#!/usr/bin/env sh
# ccopilot – Auto-generated by CC-Switch
# Wraps the 'copilot' command with BYOK environment variables.
#
# Usage: ccopilot [args...]
# Setup: add ~/.cc-switch to PATH, or run:
#   ln -sf ~/.cc-switch/ccopilot ~/.local/bin/ccopilot
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/copilot-env.sh"
exec copilot "$@"
"#;
    let sh_path = dir.join("ccopilot");
    fs::write(&sh_path, sh_wrapper).map_err(|e| {
        AppError::localized(
            "copilot.write_wrapper_sh_failed",
            format!("写入 ccopilot 脚本失败: {e}"),
            format!("Failed to write ccopilot wrapper script: {e}"),
        )
    })?;

    // Unix：赋予执行权限
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&sh_path)
            .map_err(|e| {
                AppError::localized(
                    "copilot.chmod_failed",
                    format!("读取 ccopilot 文件权限失败: {e}"),
                    format!("Failed to read ccopilot permissions: {e}"),
                )
            })?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&sh_path, perms).map_err(|e| {
            AppError::localized(
                "copilot.chmod_failed",
                format!("设置 ccopilot 执行权限失败: {e}"),
                format!("Failed to set ccopilot executable permission: {e}"),
            )
        })?;
    }

    // ── PowerShell 包装脚本（Windows / 跨平台 pwsh）──
    let ps1_wrapper = "# ccopilot.ps1 – Auto-generated by CC-Switch\r\n\
# Wraps the 'copilot' command with BYOK environment variables.\r\n\
#\r\n\
# Usage: & ~/.cc-switch/ccopilot.ps1 [args...]\r\n\
# Setup: add ~/.cc-switch to $env:PATH, or create a profile alias:\r\n\
#   Set-Alias ccopilot \"$env:USERPROFILE\\.cc-switch\\ccopilot.ps1\"\r\n\
\r\n\
. \"$PSScriptRoot\\copilot-env.ps1\"\r\n\
copilot @args\r\n";
    fs::write(dir.join("ccopilot.ps1"), ps1_wrapper).map_err(|e| {
        AppError::localized(
            "copilot.write_wrapper_ps1_failed",
            format!("写入 ccopilot.ps1 失败: {e}"),
            format!("Failed to write ccopilot.ps1 wrapper: {e}"),
        )
    })?;

    // ── Windows CMD 批处理（调用 PowerShell 脚本，方便直接在 cmd.exe 中使用）──
    let cmd_wrapper = "@echo off\r\n\
REM ccopilot.cmd – Auto-generated by CC-Switch\r\n\
REM Wraps the 'copilot' command with BYOK environment variables.\r\n\
REM Setup: add %USERPROFILE%\\.cc-switch to PATH\r\n\
powershell -ExecutionPolicy Bypass -File \"%~dp0ccopilot.ps1\" %*\r\n";
    fs::write(dir.join("ccopilot.cmd"), cmd_wrapper).map_err(|e| {
        AppError::localized(
            "copilot.write_wrapper_cmd_failed",
            format!("写入 ccopilot.cmd 失败: {e}"),
            format!("Failed to write ccopilot.cmd wrapper: {e}"),
        )
    })?;

    Ok(())
}

/// 从 settingsConfig JSON 对象中提取 Copilot env vars
///
/// settingsConfig 顶层的所有字符串字段均视为 env var 键值对。
pub fn extract_env_vars(config: &serde_json::Value) -> HashMap<String, String> {
    let mut vars = HashMap::new();
    if let Some(obj) = config.as_object() {
        for (k, v) in obj {
            if let Some(s) = v.as_str() {
                if !s.is_empty() {
                    vars.insert(k.clone(), s.to_string());
                }
            }
        }
    }
    vars
}
